### ISSUE TITLE
trial.sh does not support compiling with Dynamics.

### ISSUE THREAD

**Issue by thomwiggers** [squell/bb-scripts#24]
Using this works for me:

    ~/clean/bin/clm -h 100m -s 200M -dynamics -I .  -I ~/clean/lib/Dynamics -I ~/clean/lib/StdEnv -I ~/git/FP_2011_Uitwerkingen/ -I ~/clean/lib/Gast -I ~/clean/lib/Generics -I ~/clean/lib/MersenneTwister -I ~/clean/lib/StdLib  StdDynSetTest

**Comment by squell** [comment]
Didn't know "-dynamics" was a thing.

**Comment by squell** [comment]
Fixed in a72cf47
