### ISSUE TITLE
feedback.sh twee keer draaien geeft dubbele regels in grades.csv

### ISSUE THREAD

**Issue by camilstaps** [squell/bb-scripts#31]
Als je feedback.sh twee keer draait (bijvoorbeeld omdat je een cijfer vergeten bent in te voeren), komen alle regels die de eerste run wel heeft gehad dubbel voor in grades.csv. In blackboard zie je dan ook twee entries in de grade history. Het zou mooi zijn als de oude regel uit grades.csv werd gehaald.

**Comment by squell** [comment]
Hmm, is dit opgelost als je dubbele entries filtert in upload.sh? Ik neem aan dat als je een cijfer vergeet je feedback.sh onderbreekt voordat je bij het uploaden aankomt?

**Comment by camilstaps** [comment]
Dat zou inderdaad ook kunnen. Ik verwacht dat ergens `sort grades.csv | uniq | sponge grades.csv` voldoende is, maar waar precies is de vraag.

**Comment by squell** [comment]
Ik maak het iets fancier, voor't geval je grades wil herzien, ik denk dat (basically) tac grades.csv | sort -u -k1,1 -t, | sponge grades.csv ergens in upload.sh wel werkt.

**Comment by squell** [comment]
Zie: 1786a2a50912ee5f35e3e53264298ed9a1447f67

Zit vooralsnog in de experimental branch.

**Comment by squell** [comment]
Gemerged met 'master', closing.
