### ISSUE TITLE
Translating LEESMIJ.TXT to English

### ISSUE THREAD

**Issue by squell** [squell/bb-scripts#42]
The documentation (LEESMIJ.TXT) does not cover all scripts. Documentation does not need to be extensive, but a brief overview of what all scripts do is nice.

**Comment by ildyria** [comment]
The documentation shall also be written in a English (because some of us don't speak Dutch).
Idem for the comments in the files. ;)

**Comment by squell** [comment]
I think the comments part is a valid point, working on it: 2f326e12cca8b6af0d03c873826b6d9977cf993e

Perhaps @camilstaps can translate his contributions. 

I am prepared to translate LEESMIJ if I can be convinced enough non-Dutch speakers are interested in reading it. I think the Google translation is not too bad, at the moment:
https://translate.google.com/translate?hl=en&sl=nl&tl=en&u=https%3A%2F%2Fraw.githubusercontent.com%2Fsquell%2Fbb-scripts%2Fmaster%2FLEESMIJ.TXT

**Comment by camilstaps** [comment]
Done, except for rgrade.sh; I suggest to wait until #43 is merged or rejected.

**Comment by squell** [comment]
Translations have been merged into the master branch: c70be3891406672ccadfd3df78e20ddd1d286847.

I'll leave this issue open in case someone wants to translate LEESMIJ.TXT.

**Comment by squell** [comment]
Since LEESMIJ will be gone pretty quickly, this issue is now closed. :)
