### ISSUE TITLE
Blackboard internationalisation workaround

### ISSUE THREAD

**Issue by camilstaps** [squell/bb-scripts#44]
When trying to upload a grades.csv to Blackboard where your Blackboard language is not English, the upload will fail. The `Username` column in the CSV is presumed to be in the language of your Blackboard interface.

I suggest that, in `upload.sh`, we look at the `lang` attribute of the `html` tag to determine the language and then change the first line of `grades.csv` accordingly before uploading.

**Comment by squell** [comment]
Possible solutions:

1) Be lazy: tell people that they need to set Blackboard to English for these scripts to work (and mention something to this effect in the readme / oral tradition surrounding these scripts).
2) What you propose
3) Download a fresh grades.csv in upload.sh

Even though I don't mind it if you try the second approach, I don't think the first solution is that bad. The problem with 2) is that it sounds like a maintenance hell -- won't we have to keep hardcoding Blackboard's translation of 'Username' to the csv files?

**Comment by camilstaps** [comment]
This is basically option 1 for people who don't read the manual: warn them when it goes wrong, but don't try to fix anything.

**Comment by squell** [comment]
Agreed: complaining beats silently failing. And if we can complain we can also safely implement 2), of course.

**Comment by camilstaps** [comment]
Yes, but as you said, it would have to be maintained...

**Comment by squell** [comment]
Well, in that case 2) is simply a slightly more general version of 1): English/Dutch/German is supported, but nothing else. :)
