### ISSUE TITLE
The end of BlackBoard

### ISSUE THREAD

**Issue by squell** [squell/bb-scripts#48]
As you will already know, Radboud is leaving BlackBoard behind: https://www.voxweb.nl/nieuws/radboud-universiteit-neemt-afscheid-blackboard 

It does mean that the usefulness of the current scripts will be dramatically reduced after september 2018.

I think there are three scenarios:

1.  The successor system will be much more friendly to use, and we don't need silly bash scripts anymore.

2. It turns out to be helpful to retain (some) functionality; i.e. the scripts need to be ported. This might be not that big a issue; even minor upgrades to BlackBoard have caused pain in the past, and this might be a good time to switch to the official API (if possible).

3. We can detach bb-scripts to not require BlackBoard at all, so the scripts don't sink with the rest of the ship. The simplest way (from the point of view of what we expect students to do and the amount of additional scripting infrastructure needed) is to automate handing in stuff via email. Using a proper server-side Sieve filter, we could sort mail into a IMAP folder and then let a script transform this to the usual s0123456 directory structure. A prototype of this is in the imap branch already.

Let's hope for scenario 1, expect to have to work on scenario 2, and keep scenario 3 as a undesirable fallback that only has to provide some bare functionality.

**Comment by camilstaps** [comment]
Even in scenario 1 I think these scripts will still be helpful for at least the following:

- Plagiarism checks
- Automated testing
- The rgrade workflow

It looks like Brightspace has quite a lot of documentation and SDKs available (http://docs.valence.desire2learn.com/index.html; https://brightspace.github.io/). But we'll have to see how much is possible already and if it is sensible to continue with bash or move to a language that has an SDK (looks like python is the most logical choice from that list).

I have also been [epibrating](https://nl.wikipedia.org/wiki/Epibreren) making a Brightspace wrapper that pretends it is Blackboard so that we can still use these scripts ... but I guess that idea is not going to make it :)

**Comment by squell** [comment]
That is, in fact, more or less what I mean with scenario 2.

Globally, the functionality that the scripts provide is a.) making the content from the electronic learning environment accessible for easy manipulation at the filesystem level and b.) scripts that operate purely on the filesystem level, like testing, printing, sending mail, etc.

With (a) being the necessary evil that requires a yearly rewrite of some regexes and (b) being fairly stable.
To interface with BrightSpace, we would "only" need to replace the evil parts (a), i.e. bblogin2.sh+getsch.sh+bbfix.sh(+upload.sh). Doing that by writing a Python program that acts like glue between bash and the SDK sounds like the cheapest way to do it (and if the SDK sucks, a pure bash solution with `curl` + `jq` is probably also not that much work)

The bottleneck for scenario 2 is that we need early access to BrightSpace (with a fake course and fake handins, etc) so we can understand how it works and test the system before the relevant courses start in september '18. Right now I don't know the time schedule for adoption :(

**Comment by camilstaps** [comment]
[This](http://www.ru.nl/nieuws-agenda/vm/studentennieuwsbrief-0/blackboard-2018-vervangen-brightspace/) gives a rough time schedule and a contact email address that we can maybe use to ask for early access.

**Comment by squell** [comment]
More info: https://www.radboudnet.nl/ictineducation/projects/digital-learning-environment/digital-learning-environment/frequently-asked-questions-on-brightspace/

So apparently, in early 2018, we may be able to start hacking.

**Comment by dsprenkels** [comment]
The page does not seem to load with my (s-number) account. Could you quote it or copy-paste it to a gist?

**Comment by thomwiggers** [comment]
>**When can I get my first glimpse of Brightspace?**
>The first Radboud-Brightspace test environment will be introduced in early 2018. You will then be able to try out Brightspace for yourself, without it having any implications on the current learning environment. Visit Radboudnet.nl/lms regularly to stay informed.

**Comment by squell** [comment]
Update: I've talked to the BrightSpace project manager, who gave me a brief demo of the grading system in BrightSpace works to assess what need we would still have of our scripts.

It turns out that in BrightSpace, the 'grading offline' option is much more sensible than in BlackBoard: you can basically download a .zip containing a directory structure (instead of the flat zip with mangled filenames that BlackBoard gives you), put feedback inside each directory somewhere, and then re-zip the entire thing and upload it back. That sound very similar to how these scripts work.

See:
https://brightspace-support.tudelft.nl/qrc-training/grading-paperless-assignments-brightspace/

So, in the future, I expect the functionality of getsch.sh, upload.sh and mailto.sh will simply be unnecesary (perhaps mailto.sh can be argued, but putting feedback *inside* the ELO, seems preferable to email to me). Of course it will be a bit more manual clicking, but I don't see a huge problem.

Also, BrightSpace supports creating "groups" of students (who can submit something collectively), so probably 'groups.sh' (which tries to guess who the other person is that should also receive feedback) is something we don't need anymore as well, *if* teachers set up their courses correctly.

That still leaves the question of how to implement functionality like distributing work; but since most of that part of these scripts (antifmt.sh, hak2.sh, etc) assume the existence of a directory structure, and BS can give us that, porting that part is probably a matter of a changing a couple of lines. 

Overall, I am optimistic.

**Comment by MareinK** [comment]
Since courses using Brightspace are starting now, has there been any progress on the conversion? Or any way to contribute?

**Comment by thomwiggers** [comment]
Someone would have to set up a course to experiment with first, I think.

**Comment by squell** [comment]
More things you can test in week 1: in BrightSpace assignments, there are several options how many times students can submit a solution:

1. All submissions are kept
2. Only the most recent submission is kept.
3. Only one submission is allowed.

I think it is clear that (1) and (3) mean for the ZIP, but what about (2)?

**Comment by squell** [comment]
Did some initial work on the `brightspace` branch, which is now also the default branch displayed in GitHub.

**Comment by paulkamsteeg** [comment]
Since an adaptation of your scripts has been used in one of my courses for some years, I have asked TIP, the "Teaching Information Point FSW" (the Brightspace people of FSW) if they could adapt the Blackboard side to Brightspace. Robert Klaassen of TIP has taken it up. It might be useful  to coordinate with him, if only to avoid double work. He can be reached at tip@socsci.ru.nl
Paul Kamsteeg

**Comment by squell** [comment]
I have been playing around with a sandbox and compiled a short manual, which is now on the Wiki. As far as I know this Wiki editable by everyone, so that is also one way people can contribute.

**Comment by squell** [comment]
As far as I can tell, the scripts are still/again being used and being useful. I have not had any assistance (or was asked for assistance) by any of the TIP@ support people, but where the scripts in early september were lacking, teaching assistants have quickly implemented a solution. 

So basically, business as usual. Closing this issue.
