### ISSUE TITLE
bb-scripts fail bad when not having a program

### ISSUE THREAD

**Issue by dopefishh** [squell/bb-scripts#55]
I suggest using `set -e` in all scripts (I can do that tomorrow).
Tomorrow I will test the scripts for a course I assist:)

ps. I know the scripts are supposed to run on lilo but still

**Comment by dopefishh** [comment]
Maybe set -e is a bit aggressive, but checking would be nice (i'll make pr)

**Comment by squell** [comment]
I think it's a good idea (in principle) to use set -e anywhere instead of in just the places where failures will really mess things up. But sometimes a failure is acceptable, e.g. failure when unzipping a ZIP file should probably not cause antifmt.sh to stop processing.
