### ISSUE TITLE
#comments should be HTML entity decoded

### ISSUE THREAD

**Issue by dopefishh** [squell/bb-scripts#58]
The #comments file is an html file, sort of.
Dumping it with `w3m` or `lynx` is not an option because newlines are not encoded.

Therefore I propose to just decode the html entities.

Snippet of `#comments` I encountered:
```
:k Bin
* -&gt; *
```

**Comment by squell** [comment]
Initially I piped the content for #comments through `html2text`, but then I saw at least two cases of funny business going on the comments (anyone fancy a <script> tag?) so I actually put in some extra effort to show the raw HTML so we can actually see that happening. But you are right, the HTML entities are an eyesore...

Perhaps we should do #raw_comments and #comments?

**Comment by dopefishh** [comment]
only #comments is fine by me.
I even encountered a `&nbsp;` just yet:')
