### ISSUE TITLE
ATT00001.txt instead of mail body (sometimes)

### ISSUE THREAD

**Issue by W-M-T** [squell/bb-scripts#65]
I've gotten messages from a couple of students each week that some feedback mails they receive are empty and instead have an attached file named ```ATT00001.txt``` which contains the text that composes the mail body for most other students.
The strange thing is that it doesn't seem to happen consistently. Most sent feedback mails do not have this.

**Comment by dopefishh** [comment]
This is most likely a mailserver issue. My hypothesis is that all studentes forward this mail te their own sane mail server except a merry few that use the exchange facilities or webmail from the RU.
Google ATT00001.txt and you get myriads of hits fort exchange not healing correctly with some attachment formats.

**Comment by squell** [comment]
Could you indicate whether you tried this, and whether it solved the issue for you?
