### ISSUE TITLE
Colon in paths

### ISSUE THREAD

**Issue by dopefishh** [squell/bb-scripts#66]
As of right now there are colons in the path of the student directories.
This is not a direct problem on sane OS's but it is if you need the directory in a pathstring.
Pathstrings on linux are separated by : and that will cause unexpected problems.

For example, `cpm` from clean will bork out in `cocl` if it produces directories with `:`.
I propose to remove the : from the directory

**Comment by dopefishh** [comment]
Cpm may create absolute paths in some cases. It doesn't necessarily have to but does it anyway.

I'll make a PR

**Comment by squell** [comment]
This PR broke the 'getcomment' macro in bsunzip.sh. Working on a fix.

**Comment by squell** [comment]
Closed by 750f98
