### ISSUE TITLE
Permission denied while trying to adjust for student creativity

### ISSUE THREAD

**Issue by kliyer-ai** [squell/bb-scripts#73]
In particular, this happens during the rm command:
![issue](https://i.imgur.com/SIFzPEx.png)

**Comment by squell** [comment]
Sorry for not noticing this earlier. Have you been able to solve it? Otherwise; can you send me the .zip file (by email) that contains these submissions?

**Comment by squell** [comment]
Closing as this issue as 3+ years old and probably resolved in some other way by now :)
