### ISSUE TITLE
plagiarism script should support blacklisting files

### ISSUE THREAD

**Issue by mklinik** [squell/bb-scripts#75]
For OO we provide project templates to students where they just have to fill in some of the classes. This causes a lot of false positives in the plagiarism detection script for files that students don't have to touch.

It would be nice to have a list of files to be ignored by the plagiarism script.

**Comment by squell** [comment]
Take a look in the `fp` branch; we had the same problem in the FP course some years ago; there both `plaggen.sh` and `dupes.sh` contains a loop to filter out signatures of the templates given to students (that students are not supposed to alter drastically).

This functionality was removed when these scripts were ported over to the master branch, it should be easy to put back in.

**Comment by mklinik** [comment]
Thanks! I'll have a look.
